### ISSUE TITLE
escape query HOC with conditionals

### ISSUE THREAD

**Issue by dankram** [cantierecreativo/redux-bees#11]
Currently I want to do something like this:

```js
@query('categories', ingester.getCategories, (perform, {params}) => {
  if (!params.categoryId) {
    return perform()
  }
})
```

But because query always expects a function to be returned I have to do this:

```js
@query('categories', ingester.getCategories, (perform, {params}) => {
  if (!params.categoryId) {
    return perform()
  }
  return () => {}
})
```

**Comment by stefanoverna** [comment]
Hi @dankram, I don't want to over-complicate the query HOC, so I would suggest you only to wrap your component in a query HOC when you really need it.. you can use the [`branch` HOC of the recompose lib](https://github.com/acdlite/recompose/blob/master/docs/API.md#branch) for that:

```js
import React from 'react';
import api from '../ingester';
import { query } from 'redux-bees';
import { branch } from 'recompose';

@branch(
  (props) => !props.params.categoryId,
  query('categories', ingester.getCategories),
)

export default class App extends React.Component {
...
```

**Comment by stefanoverna** [comment]
Updated the README: https://github.com/cantierecreativo/redux-bees/blob/master/README.md#conditional-fetch
