### ISSUE TITLE
Execute specific code after every request

### ISSUE THREAD

**Issue by Michaelvilleneuve** [cantierecreativo/redux-bees#12]
I would like to redirect to my login page if any request returns 401. How can I do that ? Is there a way to listen to any request result ?

**Comment by stefanoverna** [comment]
@Michaelvilleneuve just added middlewares! https://github.com/cantierecreativo/redux-bees#resolvereject-middlewares

**Comment by Michaelvilleneuve** [comment]
Awesome 👍 👍  thank you !
