### ISSUE TITLE
API call cannot be performed. The following params were not specified: index

### ISSUE THREAD

**Issue by Mirigan** [cantierecreativo/redux-bees#25]
I have a problem for my routes, I try to call a route with 2 params in it but a got the following message : `API call cannot be performed. The following params were not specified: index`

Here the declaration of my route 
`endPoind: { method: destroy, path: '/api/model/:id/subModel/:index' }`

And here how I call it 
`Api.endPoind({ id: 12, index: 0 })`

If someone have any idea to resolve it, or if do something bad

**Comment by ifiokjr** [comment]
Without diving into this deeper, it looks like this line could be at fault. 

https://github.com/cantierecreativo/redux-bees/blob/cad2d4cdb26dabd6c188150b100b2ee3249f2a32/src/buildApi.js#L46

The number`0` is a falsey value and your `index` will be placed into the `missingPlaceholders` causing the error. 

Try passing the `0` as a string.

```js
Api.endPoind({ id: 12, index: '0' }) // '' + 0
```

**Comment by stefanoverna** [comment]
you're right! will fix it, thanks

Il 06/ott/2017 08:37, "Ifiok Jr." <notifications@github.com> ha scritto:

**Comment by Mirigan** [comment]
Thanks guys for your help, now it works 😄

**Comment by stefanoverna** [comment]
released 0.1.7
