### ISSUE TITLE
Accessing top-level response object?

### ISSUE THREAD

**Issue by benjy** [cantierecreativo/redux-bees#65]
Is it possible to access the top level response object per API call?

**Comment by dlikhten** [comment]
Heh, late response. No. But why would you need to?

`getRequestInfo` gives you lots of useful data:

- results
- meta (where any weird props should go)

The only thing not immediately available is includes, but those can easily be traversed via the `getRelationship`

**Comment by benjy** [comment]
I think my use case was accessing some information drupal sent back in the "links" key at the top level but I can't remember now, i've moved away from this library instead. Thanks.
