### ISSUE TITLE
The future of the library and other issues

### ISSUE THREAD

**Issue by vlanemcev** [cantierecreativo/redux-bees#8]
Hello, Stefano!
I liked your library for interacting redux and json-api. Great work!
https://github.com/cantierecreativo/redux-bees

But I have a few questions for you, as a developer.
- How long will you support this library?
I would like to use your solution on my project, but I want to be sure that I will not see the library through time with status - it is not supported.

- How confident can you use this library for prouction?
I mean, is it well tested and will there be any drastic changes to the API in the future?

- What browser support does your library have?
I saw that you are using the fetch and promise method to communicate with the server. Maybe there are some other ways to communicate with the server to support older browsers.

**Comment by stefanoverna** [comment]
Hi @vlanemcev, this library is still in early stage. We're running on a couple of projects in production, but there might be API changes in the future to adapt it to developers requests. We rely on fetch, yep, so you need a polyfill for that (will add to the readme, thanks!)
