### ISSUE TITLE
Add a meta field

### ISSUE THREAD

**Issue by vlanemcev** [cantierecreativo/redux-bees#9]
Hi, @stefanoverna !
In the json-api specification, it is possible to create a **meta** field in a resource object and pass non-standard meta-information there.
http://jsonapi.org/format/#document-top-level
Sometimes this is useful and you need to keep this information in the state of our application.
For my application, this is exactly what I need, but I was faced with the fact that the library does **not add** meta information anywhere.

I analyzed the code and thought about how and where to add this meta-object.
I think it's best to do this in  [reducers/entities.js](https://github.com/cantierecreativo/redux-bees/blob/master/src/reducers/entities.js#L37) in line number 37, you can just add the code:

` 
if(meta) {
			newState = immutable.set(
				newState,
				'meta',
				meta
			);
		}`

**Comment by stefanoverna** [comment]
good point @vlanemcev, would you be willing to submit a PR?

**Comment by vlanemcev** [comment]
In my pull request I meant to add a meta field to the **entities** property so that it can be accessed as a resource field object.
It seems to me that the name "getRequestMeta" is not very correct, since I meant the meta data of the resource object, not the entire query.

**Comment by vlanemcev** [comment]
I re-read the JSON API specification.
I think that you did everything right. There are no more questions.

**Comment by stefanoverna** [comment]
:+1
